# -*- coding: utf-8 -*-
"""Despliegue_ValidacionCruz_Clasif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVu5A5M5mzzXzeSokS988omLPF5TqGp-

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-cla.pkl'
modelo, labelencoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))
#modelo

#Cargamos los datos futuros
#data = pd.read_csv("ataque_corazon-datosFuturos.csv")
#data.head()



#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.set_page_config(page_title="Predicción de Ataque al Corazón", page_icon="❤️", layout="centered")

st.markdown("""
    <style>
    .stApp { background: linear-gradient(160deg, #0f2027 0%, #203a43 50%, #2c5364 100%); color:#f5f6fa; }
    label, .stSelectbox label, .stSlider label { color:#eaf0f1 !important; font-weight:600 !important; }
    div.stButton > button {
        background: linear-gradient(90deg, #ff5f6d 0%, #ffc371 100%);
        color:#1a1a1a; font-weight:700; border:none; border-radius:12px; padding:0.6rem 1.4rem; width:100%;
    }
    div.stButton > button:hover { box-shadow:0 8px 20px rgba(255,95,109,0.35); color:#000; }
    </style>
""", unsafe_allow_html=True)

st.title('❤️ Predicción de Ataque al Corazón')
st.caption('Modelo Random Forest — ingresa los datos del paciente')

age = st.slider('Edad', min_value=1, max_value=82, value=45, step=1)
avg_glucose_level = st.slider('Nivel promedio de glucosa', min_value=55.0, max_value=272.0, value=100.0, step=0.1)
hypertension = st.selectbox('Hipertensión', ['No', 'Yes'])
heart_disease = st.selectbox('Enfermedad cardíaca', ['No', 'Yes'])
ever_married = st.selectbox('Alguna vez casado/a', ['No', 'Yes'])
smoking_status = st.selectbox('Estado de fumador', ["'never smoked'", "'formerly smoked'", "smokes", "Unknown"])


#Dataframe
datos = [[age, avg_glucose_level, hypertension, heart_disease, ever_married, smoking_status]]
data = pd.DataFrame(datos, columns=['age', 'avg_glucose_level', 'hypertension', 'heart_disease', 'ever_married', 'smoking_status']) #Dataframe con los mismos nombres de variables

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 8% (mape: error porcentual)")

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status', 'hypertension', 'heart_disease', 'ever_married'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#Como el modelo final es Random Forest (árboles) NO se normaliza -> se deja comentado
#data_preparada[['age','avg_glucose_level']]= min_max_scaler.transform(data_preparada[['age','avg_glucose_level']])
#data_preparada.head()

"""# Predicción"""

#Hacemos la predicción con el Random Forest
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

#Se convierte 0/1 a la etiqueta original (No/Yes)
Y_pred_etiqueta = labelencoder.inverse_transform(Y_pred)
data['Prediccion']=Y_pred_etiqueta
data.head()